### PR TITLE
starter-jni: Fix all the things

### PR DESCRIPTION
**Pull request by sirmordred**
* Fix memory leaks
* Removed unused variables
* Backported for C99 standarts
* Now buildable with Android.mk-style ndk compilation

### CODE REVIEW

**Comment by sirmordred** [comment]
@RikkaW @haruue  if you have Telegram, it would be good to discuss further improvements etc on there :+1:

**Comment by sirmordred** [comment]
@haruue @RikkaW  i'm considering to add Shell API support for app developers who can get benefit from it, like Chainfire's libsuperuser's Shell.SH.run(command) implementatiıon(https://github.com/Chainfire/libsuperuser/blob/master/libsuperuser/src/eu/chainfire/libsuperuser/Shell.java#L239), but i'm not sure how can i initiate "adb shell commands" after getting server running, i'm still making some more research on it, i found this one https://github.com/android/platform_development/tree/master/samples/USB/AdbTest and it seems after getting server running, we can send data(commands etc) through opened scoket port via outputStream and get results from scoket's inputStream, i'll try it, but not sure if it will work or not, do you guys have an any idea?

**Comment by sirmordred** [comment]
Ok probably there is no development on this app anymore, closing it

**Comment by haruue** [comment]
@sirmordred 
Sorry, we are busy in another project (AppOps) recently and @RikkaW forgot merge your pull request.

If you want to add Shell API support, you can just add a method whose behavior likes libsuperuser's `Shell.SH.run(command)`. This is a simple guide to add a api to Shizuku Manager.

1. Add your method signature into the [apis.aidl](https://github.com/RikkaW/Shizuku/blob/master/apis.aidl) in AIDL syntax.
2. Build the [generator](https://github.com/RikkaW/Shizuku/tree/master/generator)
``` shell
cd <project-root>/generator
gradle build
```
3. Invoke the generator
```shell
cd <project-root>/generator
java -cp build/libs/generator.jar moe.shizuku.AidlParser api
java -cp build/libs/generator.jar moe.shizuku.AidlParser server
```
4. Implement your method in [SocketThread.java](https://github.com/RikkaW/Shizuku/blob/master/server/src/main/java/moe/shizuku/server/SocketThread.java)
5. Make a pull request to this project to publish you new API. 

@RikkaW is hesitating about the way to add API, because it still need to do a lot to add all hidden or privileged API of Android. And the current way may be deprecated when a new way comes out. It is also why we don't have a reference for developer and contributor yet. 

And in my personal opinion, Shell API is not necessary. Because nearly all function which can be implement with shell will also be able to implement with system hidden api. For a example, the shell command [`pm`](https://android.googlesource.com/platform/frameworks/base/+/android-8.0.0_r4/cmds/pm/pm) is just a wrapper of [`com.android.commands.pm.Pm`](https://android.googlesource.com/platform/frameworks/base/+/android-8.0.0_r4/cmds/pm/src/com/android/commands/pm/Pm.java#104). 

Thank you again for your contribution, have a nice day !

**Pull request merged**
